### ISSUE TITLE
KeyError: 'results'

### ISSUE THREAD

**Issue by Phillyclause89** [briansrls/Robinhood-for-Google-Finance#15]
I get the following error when running the script.

```
100 order fetched
200 order fetched
300 order fetched
400 order fetched
500 order fetched
600 order fetched
700 order fetched
800 order fetched
900 order fetched
1000 order fetched
1100 order fetched
1200 order fetched
1300 order fetched
1400 order fetched
1500 order fetched
1600 order fetched
1700 order fetched
1800 order fetched
1900 order fetched
2000 order fetched
2100 order fetched
2200 order fetched
2300 order fetched
2400 order fetched
2500 order fetched
2600 order fetched
2700 order fetched
2800 order fetched
2900 order fetched
3000 order fetched
3100 order fetched
3200 order fetched
3300 order fetched
3400 order fetched
3500 order fetched
3600 order fetched
3700 order fetched
3800 order fetched
3900 order fetched
4000 order fetched
4100 order fetched
4200 order fetched
4300 order fetched
4400 order fetched
4500 order fetched
4600 order fetched
4700 order fetched
4800 order fetched
4900 order fetched
5000 order fetched
5100 order fetched
5200 order fetched
5300 order fetched
5400 order fetched
5500 order fetched
5600 order fetched
5700 order fetched
5800 order fetched
5900 order fetched
6000 order fetched
Traceback (most recent call last):
  File "gf-export.py", line 52, in <module>
    past_orders = get_all_history_orders(robinhood)
  File "gf-export.py", line 45, in get_all_history_orders
    orders.extend(past_orders['results'])
KeyError: 'results'
```

**Comment by briansrls** [comment]
Hello,

Is this the first time you've ran this script?  If not, have you been successful until now?

Oh, and please include what version of python you're using please.

Thanks

**Comment by Phillyclause89** [comment]
I'm using Python 3.6.4. Last night was the first time I tried running the script.

**Comment by briansrls** [comment]
Could you try using python 2.7?  If that works, I will look into adding support for 3.6.4.  Please let me know if you'll need help setting sup python 2.7.
