### ISSUE TITLE
ImportError: No module named enum

### ISSUE THREAD

**Issue by sudkish** [briansrls/Robinhood-for-Google-Finance#16]
I get the below error when I run `python gf-export.py`. Can you help fix this issue?
> Traceback (most recent call last):
>   File "gf-export.py", line 1, in <module>
>     from Robinhood import Robinhood
>   File "/Users/user/Documents/Robinhood-for-Google-Finance/Robinhood/__init__.py", line 6, in <module>
>     from Robinhood import Robinhood
>   File "/Users/user/Documents/Robinhood-for-Google-Finance/Robinhood/Robinhood.py", line 7, in <module>
>     from enum import Enum
> ImportError: No module named enum

**Comment by sudkish** [comment]
Resolved with `pip install --ignore-installed enum`
